spring:
  profiles:
    active: dev

server:
  servlet:
    context-path: /api

---
spring:
  profiles: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    continue-on-error: true
    url: jdbc:postgresql://localhost:5433/reclamos
    username: elias
    password: admin123

server:
  port: 8090

---
spring:
  profiles: pdn
  datasource:
    url: jdbc:postgresql://172.19.0.3:5432/reclamos
    username: elias
    password: admin123
server:
  port: 80
